name: Deploy Company Service

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "company-service/*"

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    defaults:
      run:
        working-directory: ./company-service

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Company Service to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "xploration-company-svc"
          heroku_email: ${{secrets.HEROKU_API_KEY}}
        env:
          HD_APP_BASE: "company-service"
            
  schema_push:
    name: Generate & Schema Push
    runs-on: ubuntu-latest
    needs: deploy

    strategy:
      matrix:
        node-version: [15.x]

    defaults:
      run:
        working-directory: ./company-service

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Generate Local Schema for Company Service
        run: |
          npm ci && npm run generateSchema

      - name: Push Company Schema to Apollo Registry
        env:
          APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
        run: |
          npx -p @apollo/rover rover subgraph publish xploration-graphql-ygvmgl \
            --name=xploration-company-svc \
            --schema=./schema.graphql \
