name: Deploy Roadster Service to Heroku

on:
  push:
    branches:
      - main
    paths:
      - "src/roadster-service/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release Roadster Service
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "xploration-roadster-svc"
          heroku_email: ${{secrets.HEROKU_API_KEY}}
        env:
          HD_APP_BASE: "src/roadster-service"