name: Deploy Company Service to Heroku

on:
  push:
    branches:
      - main
    paths:
      - "company-service/*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Release Company Service
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "xploration-company-svc"
          heroku_email: ${{secrets.HEROKU_API_KEY}}
        env:
          HD_APP_BASE: "company-service"

      - name: Generate Local Schema for Company Service
        uses: actions/setup-node@v2
        working-directory: ./company-service
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run generateSchema
